### ISSUE TITLE
[PROPS] Best thing evar

### ISSUE THREAD

**Issue by Darkcast** [j3ssie/Metabigor#1]
Thanks for your hard work on this tool, you have saved my arse hours of coding. now I can continue to sit in my lawn chair and scream to the kids GET OFF MY LAWN. 
but seriously great work man :)

[https://i.imgflip.com/166ocy.jpg](url)

**Comment by j3ssie** [comment]
Thank you. More features will come soon :).

> P/s: Ever notice how you come across some tool once in a while you shouldn't have f***ed with? That's probably this tool :)
From [Gran Torino](https://www.imdb.com/title/tt1205489/)

**Comment by Darkcast** [comment]
> Thank you. More features will come soon :).
> 
> > P/s: Ever notice how you come across some tool once in a while you shouldn't have f***ed with? That's probably this tool :)
> > From [Gran Torino](https://www.imdb.com/title/tt1205489/)

(JOKE) coding and women have ruined my life 
HAHAHAHA
