### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gitxmax** [j3ssie/metabigor#11]
home@ubuntu:~/main/Metabigor# ./metabigor.py -s fofa -q "test"
Traceback (most recent call last):
  File "./metabigor.py", line 7, in <module>
    from core import config
  File "/root/main/Metabigor/core/config.py", line 11, in <module>
    from . import utils
  File "/root/main/Metabigor/core/utils.py", line 42
    print(f'{GR}' + '-'*40)
                ^
SyntaxError: invalid syntax

**Comment by j3ssie** [comment]
Due to Metabigor upgraded into v1.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.

**Comment by johndoehack** [comment]
after running new metabigor on go with the following line: " go get -u https://github.com/j3ssie/metabigor " i get: " package https:/github.com/j3ssie/metabigor: https:/github.com/j3ssie/metabigor: invalid import path: malformed import path "https:/github.com/j3ssie/metabigor": invalid char ':' "

**Comment by johndoehack** [comment]
found a solution. running the code without http/https
