### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by shanow7** [j3ssie/metabigor#14]
Hi I use go get -u github.com/j3ssie/metabigor but what next?

**Comment by j3ssie** [comment]
if you install it properly then start with this [example](https://github.com/j3ssie/metabigor#example-commands) command.

**Comment by Mohadib2** [comment]
hello , i tried to install as instructed 
received :+1: 
go: downloading github.com/spf13/cast v1.4.1
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/thoas/go-funk v0.9.2
go: downloading github.com/chromedp/chromedp v0.8.0
go: downloading github.com/spf13/cobra v1.4.0
go: downloading github.com/go-resty/resty/v2 v2.7.0
go: downloading github.com/fatih/color v1.13.0
go: downloading inet.af/netaddr v0.0.0-20211027220019-c74959edd3b6
go: downloading github.com/PuerkitoBio/goquery v1.8.0
go: downloading go4.org/mem v0.0.0-20220409205537-d9185028b2dc
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/chromedp/cdproto v0.0.0-20220408044303-8559a4e76b35
go: downloading go4.org v0.0.0-20201209231011-d4a079459e60
go: downloading inet.af v0.0.0-20181218191229-53da77bc832c
go: downloading github.com/go-resty/resty v1.12.0
go: downloading github.com/gobwas/ws v1.1.0
go: downloading github.com/gobuffalo/here v0.6.5
go: downloading github.com/andybalholm/cascadia v1.3.1
go: downloading golang.org/x/crypto v0.0.0-20220408190544-5352b0902921
go: downloading golang.org/x/sys v0.0.0-20220408201424-a24fb2fb8a0f
go: downloading golang.org/x/net v0.0.0-20220407224826-aac1ed45d8e3
go: downloading go4.org/intern v0.0.0-20220301175310-a089fc204883
go: downloading go4.org/unsafe/assume-no-moving-gc v0.0.0-20211027215541-db492cf91b37
go: downloading go4.org/unsafe v0.0.0-20201222175341-b30ae309168e
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading github.com/stretchr/testify v1.7.0
go: downloading golang.org/x/text v0.3.7
go: upgraded github.com/PuerkitoBio/goquery v1.7.0 => v1.8.0
go: upgraded github.com/chromedp/cdproto v0.0.0-20210526005521-9e51b9051fd0 => v0.0.0-20220408044303-8559a4e76b35
go: upgraded github.com/chromedp/chromedp v0.7.3 => v0.8.0
go: upgraded github.com/fatih/color v1.12.0 => v1.13.0
go: upgraded github.com/go-resty/resty/v2 v2.6.0 => v2.7.0
go: upgraded github.com/gobuffalo/here v0.6.0 => v0.6.5
go: upgraded github.com/json-iterator/go v1.1.11 => v1.1.12
go: upgraded github.com/mattn/go-colorable v0.1.8 => v0.1.12
go: upgraded github.com/spf13/cast v1.3.1 => v1.4.1
go: upgraded github.com/spf13/cobra v1.1.3 => v1.4.0
go: upgraded github.com/thoas/go-funk v0.8.0 => v0.9.2
go: upgraded go4.org/intern v0.0.0-20210108033219-3eb7198706b2 => v0.0.0-20220301175310-a089fc204883
go: upgraded go4.org/mem v0.0.0-20201119185036-c04c5a6ff174 => v0.0.0-20220409205537-d9185028b2dc
go: upgraded golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9 => v0.0.0-20220408190544-5352b0902921
go: upgraded golang.org/x/net v0.0.0-20210428140749-89ef3d95e781 => v0.0.0-20220407224826-aac1ed45d8e3
go: upgraded golang.org/x/sys v0.0.0-20210525143221-35b2ab0089ea => v0.0.0-20220408201424-a24fb2fb8a0f
go: upgraded inet.af/netaddr v0.0.0-20210603230628-bf05d8b52dda => v0.0.0-20211027220019-c74959edd3b6
********************************************
it s still not working 
kali do not recognise it as a command
meatbigor: command not found

**Comment by Prashanth00** [comment]
Yes, for me too. 
metabigor: command not found
This error shows even after proper installation.Please help

**Comment by Prashanth00** [comment]
you will find a go folder.
give command  "cd go/bin/".
Then u can use metabigor
for ex:
echo "company" | ./metabigor net --org -o /tmp/result.txt
