### ISSUE TITLE
Sorry^ but how install

### ISSUE THREAD

**Issue by Get09** [j3ssie/metabigor#15]
~/Metabigor$ ls
cmd  core  LICENSE  main.go  modules  README.md
where is "metabigor.py"?

**Comment by John33000** [comment]
Same issue, How I can install it ?

**Comment by pdelteil** [comment]
> ~/Metabigor$ ls
> cmd core LICENSE main.go modules README.md
> where is "metabigor.py"?

Hello there,
 
It's a go application, not a python one.

**Comment by pdelteil** [comment]
> Same issue, How I can install it ?

go get -u github.com/j3ssie/metabigor

But you should set the variables GOROOT and GOPATH. 

export GOROOT=/home/user/programming/go/go-1.4
export GOPATH=/home/user/programming/go/packages
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

**Comment by gudge25** [comment]
[antonio@antonio-ms7596 ~]$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/antonio/.cache/go-build"
GOENV="/home/antonio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/antonio/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
**GOPATH="/home/antonio/go"**
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
**GOROOT="/usr/lib/go"**
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build589378835=/tmp/go-build -gno-record-gcc-switches"

BUT **[sudo] go get -u github.com/j3ssie/metabigor**
DO  NOTHING

**Comment by gudge25** [comment]
ok o have foind answer 
have to wait for **go get -u github.com/j3ssie/metabigor**   ends
then there should appear directory  bin insode  GOPATH
amd file inside  directory
![image](https://user-images.githubusercontent.com/2346208/104062902-f690db00-5203-11eb-8c89-7466d19c7c75.png)

**Comment by j3ssie** [comment]
Please go to the release page and download the pre-built binaries if you have a problem installing with the go tool.
