### ISSUE TITLE
Error, no inicia sesión

### ISSUE THREAD

**Issue by victoranibarro** [j3ssie/metabigor#2]
Especifique mis credenciales en el config.conf pero recibo la siguiente respuesta:
[*] Loading session from: config.conf
[DEBUG] {'config': 'config.conf', 'query': '143.0.101.21', 'outdir': '.', 'module': 'custom', 'target': None, 'debug': True, 'relatively': False, 'brute': None, 'disable_pages': None, 'store_content': None, 'output': 'output', 'raw': 'raw', 'source': 'shodan', 'source_list': None, 'Cookies_shodan': 'None', 'Cookies_censys': 'None', 'Cookies_fofa': 'None', 'Cookies_zoomeye': 'None', 'Credentials_shodan': 'usuariodeshodan:passworddeshodan', 'Credentials_censys': 'usuariodeshodan:passworddeshodan', 'Credentials_fofa': 'username:password', 'Credentials_zoomeye': 'username:password'}
[*] Query: 143.0.101.21
--~~~[ Starting scraping from Shodan ]~~~--
[DEBUG] Checking session for Shodaan
[DEBUG] https://account.shodan.io/
[-] Look like shodan session is invalid.
[*] Reauthen using credentials from: config.conf
[DEBUG] https://account.shodan.io/login
[DEBUG] usuariodeshodan:passworddeshodan
Traceback (most recent call last):
  File "./metabigor.py", line 211, in <module>
    main()
  File "./metabigor.py", line 207, in main
    parsing_argument(args)
  File "./metabigor.py", line 50, in parsing_argument
    source_parsing(options)
  File "./metabigor.py", line 76, in source_parsing
    single_query(options)
  File "./metabigor.py", line 126, in single_query
    shodan.Shodan(options)
  File "/Users/xxx/git/Metabigor/modules/shodan.py", line 24, in __init__
    self.logged_in = self.check_session()
  File "/Users/xxx/git/Metabigor/modules/shodan.py", line 43, in check_session
    new_cookie = self.do_login()
  File "/Users/xxx/git/Metabigor/modules/shodan.py", line 281, in do_login
    self.options, really_login_url, cookies, data, follow=False)
TypeError: send_post() got an unexpected keyword argument 'follow'

**Comment by j3ssie** [comment]
what do you mean about query single IP from Shodan. Maybe you need to take a look at Shodan query syntax first.

**Comment by pkypig** [comment]
I'm having the same issue when using shodan (even if I try with one of your examples).I'm sure that It's not caused by his query. Any tips on what's causing it?

**Comment by j3ssie** [comment]
Due to Metabigor upgraded into v1.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
