### ISSUE TITLE
Doubt about installation

### ISSUE THREAD

**Issue by tXambe** [j3ssie/metabigor#20]
Hello,

I follow the steps to install metabigor , after run
```
go get -u github.com/j3ssie/metabigor
```
I've configured the variables, but I run metabigor don't run, I have this ``` sudo metabigor -h    sudo: metabigor: command not found ```

```
export GOROOT=/home/myuser/programming/go/go-1.4
export GOPATH=/home/myuser/programming/go/packages
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

Can anyone help me ?

A greeting and thanks

**Comment by j3ssie** [comment]
Please go to the release page and download the pre-built binaries if you have a problem installing with the go tool.
