### ISSUE TITLE
 cannot load hash/maphash

### ISSUE THREAD

**Issue by m7jalta** [j3ssie/metabigor#22]
$ go run main.go
build command-line-arguments: cannot load hash/maphash: malformed module path "hash/maphash": missing dot in first path element

**Comment by mobius07** [comment]
Look at here - https://github.com/mattermost/mattermost-server/issues/15337.

**Comment by MohamedFaroukAbdelazeem** [comment]
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
sudo apt install golang-go

**Comment by j3ssie** [comment]
Please go to the release page and download the pre-built binaries if you have a problem installing with the go tool.
