### ISSUE TITLE
ZoomEye

### ISSUE THREAD

**Issue by mohammed-sec2010** [j3ssie/metabigor#3]
root@kali:~/Metabigor# ./metabigor.py  -s zoomeye -q 'app:"tomcat"'

                        '@:           +#.  
                      .@@@@@        ;@@@@+ 
                      @@. ;@';#@@#;`@@``+@.
                      @'   @@@@@@@@@@.  `@#
                      @+  @@#.    .#@@  `@+
                      #@'@@;        :@@.@@ 
                       @@@;  .,      :@@@: 
                        @#  #@@@`     #@`  
                       ;@. .@+,@@     .@;  
                       #@  ,@, @@      @#  
                       @@   @@@@;      @@  
                       @@   `@@;       @@  
                       @@           .++@#  
                      #@@.         +@@@@@. 
                     `@'@#        '@#  :@@ 
                     +@`+@:       @@    :@:
                     @@  @@:      @'     @@
                     ;@.  @@#.    @+    `@+
                      @#   +@@@@@@@@`   #@`
                      '@#. `+@@@@#;@@+;@@+ 
                       '@@@@@#     .@@@@'  
                         ;@+`
            
                  Metabigor v1.0 by @j3ssiejjj

                          ¯\_(ツ)_/¯
                              
[*] Loading session from: config.conf
[*] Query: app:"tomcat"
--~~~[ Starting scraping from zoomeye ]~~~--
[-] Look like ZoomEye session is invalid.
Traceback (most recent call last):
  File "./metabigor.py", line 211, in <module>
    main()
  File "./metabigor.py", line 207, in main
    parsing_argument(args)
  File "./metabigor.py", line 50, in parsing_argument
    source_parsing(options)
  File "./metabigor.py", line 76, in source_parsing
    single_query(options)
  File "./metabigor.py", line 132, in single_query
    zoomeye.ZoomEye(options)
  File "/root/Metabigor/modules/zoomeye.py", line 27, in __init__
    self.logged_in = self.check_session()
  File "/root/Metabigor/modules/zoomeye.py", line 46, in check_session
    del self.headers['Cube-Authorization']
KeyError: 'Cube-Authorization'
root@kali:~/Metabigor#

**Comment by j3ssie** [comment]
Thanks for raise the issue I'll review it soon

**Comment by j3ssie** [comment]
Due to Metabigor upgraded into v1.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
