### ISSUE TITLE
Censys  "unexpected keyword argument 'follow' "

### ISSUE THREAD

**Issue by lilloX** [j3ssie/metabigor#4]
(Metabigor) ubuntu@ip-172-17-34-190:~/tmp/Metabigor$ ./metabigor.py -s censys -q 'test' -o listone --debug

                        '@:           +#.
                      .@@@@@        ;@@@@+
                      @@. ;@';#@@#;`@@``+@.
                      @'   @@@@@@@@@@.  `@#
                      @+  @@#.    .#@@  `@+
                      #@'@@;        :@@.@@
                       @@@;  .,      :@@@:
                        @#  #@@@`     #@`
                       ;@. .@+,@@     .@;
                       #@  ,@, @@      @#
                       @@   @@@@;      @@
                       @@   `@@;       @@
                       @@           .++@#
                      #@@.         +@@@@@.
                     `@'@#        '@#  :@@
                     +@`+@:       @@    :@:
                     @@  @@:      @'     @@
                     ;@.  @@#.    @+    `@+
                      @#   +@@@@@@@@`   #@`
                      '@#. `+@@@@#;@@+;@@+
                       '@@@@@#     .@@@@'
                         ;@+`

                  Metabigor v1.0 by @j3ssiejjj

                          ¯\_(ツ)_/¯

[*] Loading session from: config.conf
[DEBUG] {'target': None, 'disable_pages': None, 'Credentials_censys': 'lillo74:xxx', 'debug': True, 'store_content': None, 'Cookies_fofa': 'None', 'Credentials_shodan': 'username:password', 'source_list': None, 'outdir': '.', 'Credentials_fofa': 'username:password', 'raw': 'raw', 'Credentials_zoomeye': 'username:password', 'Cookies_censys': 'None', 'brute': None, 'source': 'censys', 'module': 'custom', 'output': 'listone', 'Cookies_zoomeye': 'None', 'query': 'test', 'relatively': False, 'config': 'config.conf', 'Cookies_shodan': 'None'}
[*] Query: test
--~~~[ Starting scraping from Censys ]~~~--
[DEBUG] Checking session for Censys
[DEBUG] https://censys.io/account
[-] Look like Censys session is invalid.
[*] Reauthen using credentials from: config.conf
[DEBUG] https://censys.io/login
[DEBUG] lillo74:xxx
Traceback (most recent call last):
  File "./metabigor.py", line 211, in <module>
    main()
  File "./metabigor.py", line 207, in main
    parsing_argument(args)
  File "./metabigor.py", line 50, in parsing_argument
    source_parsing(options)
  File "./metabigor.py", line 76, in source_parsing
    single_query(options)
  File "./metabigor.py", line 129, in single_query
    censys.Censys(options)
  File "/home/ubuntu/tmp/Metabigor/modules/censys.py", line 22, in __init__
    self.logged_in = self.check_session()
  File "/home/ubuntu/tmp/Metabigor/modules/censys.py", line 38, in check_session
    new_cookie = self.do_login()
  File "/home/ubuntu/tmp/Metabigor/modules/censys.py", line 266, in do_login
    self.options, really_login_url, cookies, data, follow=False)
TypeError: send_post() got an unexpected keyword argument 'follow'

**Comment by exrienz** [comment]
Got same issue here

**Comment by j3ssie** [comment]
Due to Metabigor upgraded into v1.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
