### ISSUE TITLE
pip安装完requirements.txt，运行脚本提示

### ISSUE THREAD

**Issue by aping001** [j3ssie/Metabigor#6]
要运行脚本提示 ImportError: No module named core
但是pip安装core  又找不到这个

**Comment by j3ssie** [comment]
Please use English and it's required **python3** which mean you have to use **pip3**.

**Comment by aping001** [comment]
OK,thank you very much!




------------------ 原始邮件 ------------------
发件人: "j3ssie"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 上午10:18
收件人: "j3ssie/Metabigor"<Metabigor@noreply.github.com>;
抄送: "👋  阿平"<1964003113@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [j3ssie/Metabigor] pip安装完requirements.txt，运行脚本提示 (#6)




Please use English and it's required python3 which mean you have to use pip3.
