### ISSUE TITLE
zoom  cookie无效

### ISSUE THREAD

**Issue by caizhuang** [j3ssie/metabigor#9]
![Uploading image.png…]()

**Comment by caizhuang** [comment]
![image](https://user-images.githubusercontent.com/37934655/65124701-8a470280-da27-11e9-9827-d11ca51b4402.png)
![image](https://user-images.githubusercontent.com/37934655/65125351-d1cd8e80-da27-11e9-8ff3-77184a04a0c5.png)
What is the cause of this problem, thank you for your answer！

**Comment by j3ssie** [comment]
Due to Metabigor upgraded into v1.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
